### ISSUE TITLE
Document existing WKB-based format used in Geopandas

### ISSUE THREAD

**Issue by kylebarron** [geopandas/geo-arrow-spec#10]
Currently this repo only has a brief README and a license file. The Geopandas source has a [short description](https://github.com/geopandas/geopandas/blob/9a1509476a8ce2c0092ca8fae3b1c1f5bc741c67/geopandas/io/arrow.py#L14-L32) about the metadata blob and points to this repo. Would it make sense to write a short description of this 0.1.0 format in this repository?

**Comment by brendan-ward** [comment]
I think we just need to get #2 merged, that has the full description as implemented in GeoPandas

**Comment by jorisvandenbossche** [comment]
Yeah, I have been meaning to "just merge" the metadata PR, since this is essentially already in use (by GeoPandas, but eg also R sfarrow). Will try to revive this in one of the coming days

**Comment by kylebarron** [comment]
🤦‍♂️ Sorry I came back to this repo after a while and forgot #2 existed. I'll close this issue and keep an eye on #2
